### ISSUE TITLE
dataset.py

### ISSUE THREAD

**Issue by avivkeller** [nilanjan-cse/FaceUnlock-for-PC-s#1]

**Comment by nilanjan-cse** [comment]
check if haarcascade_frontalface_default.xml file is present in the same directory as this file dataset.py
also download sqlite3 database software and create the table People with columns ID and name in it. 
Name that database file as FaceBase,db and save that in the same directory as the dataset.py . It should then work properly .

**Comment by nilanjan-cse** [comment]
check if haarcascade_frontalface_default.xml file is present in the same directory as this file dataset.py
also download sqlite3 database software and create the table People with columns ID and name in it.
Name that database file as FaceBase,db and save that in the same directory as the dataset.py . It should then work properly .

**Comment by awesomecoder3000** [comment]
Same Error
